version: "3.8"
services:

  nestapi:
    container_name: API
    build: .
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "8080:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db:

